IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'Provinces')
BEGIN
    CREATE TABLE [dbo].[Provinces] (
        [ProvinceId] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,
        [Code] [varchar](20) NULL,
        [Name] [nvarchar](100) NOT NULL
    );

    INSERT INTO [dbo].[Provinces] ([Code], [Name]) VALUES
    ('01', N'Thành phố Hà Nội'),
    ('02', N'Tỉnh Hà Giang'),
    ('04', N'Tỉnh Cao Bằng'),
    ('06', N'Tỉnh Bắc Kạn'),
    ('08', N'Tỉnh Tuyên Quang'),
    ('10', N'Tỉnh Lào Cai'),
    ('11', N'Tỉnh Điện Biên'),
    ('12', N'Tỉnh Lai Châu'),
    ('14', N'Tỉnh Sơn La'),
    ('15', N'Tỉnh Yên Bái'),
    ('17', N'Tỉnh Hòa Bình'),
    ('19', N'Tỉnh Thái Nguyên'),
    ('20', N'Tỉnh Lạng Sơn'),
    ('22', N'Tỉnh Quảng Ninh'),
    ('24', N'Tỉnh Bắc Giang'),
    ('25', N'Tỉnh Phú Thọ'),
    ('26', N'Tỉnh Vĩnh Phúc'),
    ('27', N'Tỉnh Bắc Ninh'),
    ('30', N'Tỉnh Hải Dương'),
    ('31', N'Thành phố Hải Phòng'),
    ('33', N'Tỉnh Hưng Yên'),
    ('34', N'Tỉnh Thái Bình'),
    ('35', N'Tỉnh Hà Nam'),
    ('36', N'Tỉnh Nam Định'),
    ('37', N'Tỉnh Ninh Bình'),
    ('38', N'Tỉnh Thanh Hóa'),
    ('40', N'Tỉnh Nghệ An'),
    ('42', N'Tỉnh Hà Tĩnh'),
    ('44', N'Tỉnh Quảng Bình'),
    ('45', N'Tỉnh Quảng Trị'),
    ('46', N'Tỉnh Thừa Thiên Huế'),
    ('48', N'Thành phố Đà Nẵng'),
    ('49', N'Tỉnh Quảng Nam'),
    ('51', N'Tỉnh Quảng Ngãi'),
    ('52', N'Tỉnh Bình Định'),
    ('54', N'Tỉnh Phú Yên'),
    ('56', N'Tỉnh Khánh Hòa'),
    ('58', N'Tỉnh Ninh Thuận'),
    ('60', N'Tỉnh Bình Thuận'),
    ('62', N'Tỉnh Kon Tum'),
    ('64', N'Tỉnh Gia Lai'),
    ('66', N'Tỉnh Đắk Lắk'),
    ('67', N'Tỉnh Đắk Nông'),
    ('68', N'Tỉnh Lâm Đồng'),
    ('70', N'Tỉnh Bình Phước'),
    ('72', N'Tỉnh Tây Ninh'),
    ('74', N'Tỉnh Bình Dương'),
    ('75', N'Tỉnh Đồng Nai'),
    ('77', N'Tỉnh Bà Rịa - Vũng Tàu'),
    ('79', N'Thành phố Hồ Chí Minh'),
    ('80', N'Tỉnh Long An'),
    ('82', N'Tỉnh Tiền Giang'),
    ('83', N'Tỉnh Bến Tre'),
    ('84', N'Tỉnh Trà Vinh'),
    ('86', N'Tỉnh Vĩnh Long'),
    ('87', N'Tỉnh Đồng Tháp'),
    ('89', N'Tỉnh An Giang'),
    ('91', N'Tỉnh Kiên Giang'),
    ('92', N'Thành phố Cần Thơ'),
    ('93', N'Tỉnh Hậu Giang'),
    ('94', N'Tỉnh Sóc Trăng'),
    ('95', N'Tỉnh Bạc Liêu'),
    ('96', N'Tỉnh Cà Mau');
END
